backend:
  name: github
  repo: oski13371/Palala   # ðŸ‘ˆ tu Twoje repozytorium
  branch: main

site_url: "https://oski13371.github.io/Palala"  # ðŸ‘ˆ Å›cieÅ¼ka do strony
base_url: "/Palala"

media_folder: "images/uploads"
public_folder: "/Palala/images/uploads"

collections:
  - name: "posts"
    label: "Posty"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "TytuÅ‚", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "TreÅ›Ä‡", name: "body", widget: "markdown" }
